package View;

/**
 *
 * @author LENOVO
 */
public class Check_In extends javax.swing.JFrame {

    /**
     * Creates new form Check_In
     */
    public Check_In() {
        initComponents();
        this.setLocationRelativeTo(null); 
        cargarTabla();
    }
    
    private void cargarTabla() {
    String[] columnas = {"ID Reserva", "Huésped Principal", "Fecha Entrada", "Fecha Salida", "Tipo Habitación", "Estado Check-in"};
    
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };

    // Datos simulados simulando que vienen del TXT/ArrayList en formato dd/MM/yyyy
    String[][] datosDeOrigen = {
        {"R123", "Juan Pérez", "15/05/2026", "20/05/2026", "Suite Ejecutiva", "PENDIENTE", "2", "1", "305"},
        {"R122", "María López", "15/05/2026", "22/05/2026", "Suite Estándar", "PENDIENTE", "1", "0", "201"},
        {"R124", "Carlos Ruiz", "18/05/2026", "23/05/2026", "Suite Ejecutiva", "PENDIENTE", "2", "0", "306"}
    };

    for (String[] fila : datosDeOrigen) {
        modelo.addRow(new Object[]{fila[0], fila[1], fila[2], fila[3], fila[4], fila[5]});
    }
    jTable1.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jb_Volver = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txt_CodigoReserva = new javax.swing.JTextField();
        Bt_Buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jbl_Huesped = new javax.swing.JLabel();
        Jbl_Fentrada = new javax.swing.JLabel();
        Txt_DniPas = new javax.swing.JTextField();
        Jbl_Fsalida = new javax.swing.JLabel();
        Jbl_HabSug = new javax.swing.JLabel();
        Jbl_Adulto = new javax.swing.JLabel();
        Jbl_Niños = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Cb_AsigHab = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JpanelConfirmar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelCancelar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECK-IN");

        Jb_Volver.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Jb_Volver.setForeground(new java.awt.Color(255, 255, 255));
        Jb_Volver.setText("VOLVER");
        Jb_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jb_VolverMouseClicked(evt);
            }
        });
        Jb_Volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jb_VolverKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(Jb_Volver)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Jb_Volver))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true), "BÚSQUEDA DE RESERVA (POR CÓDIGO)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Ingrese Codigo De Reserva");

        Txt_CodigoReserva.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        Bt_Buscar.setBackground(new java.awt.Color(102, 0, 0));
        Bt_Buscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Bt_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Buscar.setText("BUSCAR");
        Bt_Buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        Bt_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_BuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("o eleccione una de la lista");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_CodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Bt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_CodigoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 760, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 630, 150));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DETALLES DE LA RESERVA ACTIVA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Huesped:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Fecha Entrada:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Fecha Salida:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("DNI/Pasaporte:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Numero de Habitacion Sugerida:");

        Jbl_Huesped.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jbl_Huesped.setText("\"\"");

        Jbl_Fentrada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jbl_Fentrada.setText("\"\"");

        Txt_DniPas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Txt_DniPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DniPasKeyTyped(evt);
            }
        });

        Jbl_Fsalida.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jbl_Fsalida.setText("\"\"");

        Jbl_HabSug.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jbl_HabSug.setText("\"\"");

        Jbl_Adulto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jbl_Adulto.setText("Adultos:");

        Jbl_Niños.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Jbl_Niños.setText("Niños:");

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setText("Asignar Habitacion Diferente");

        Cb_AsigHab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cb_AsigHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_AsigHabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cb_AsigHab, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cb_AsigHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jbl_Fentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(Jbl_Huesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Jbl_HabSug, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Txt_DniPas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jbl_Fsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jbl_Niños, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbl_Adulto)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Jbl_Huesped))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Jbl_Fentrada)
                    .addComponent(Jbl_Adulto))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Jbl_Fsalida)
                    .addComponent(Jbl_Niños))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_DniPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Jbl_HabSug))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 690, 320));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true), "ESTADO DEL CHECK-IN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 3, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("PROCESO ");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setText("PENDIENTE");

        JpanelConfirmar.setBackground(new java.awt.Color(102, 0, 0));
        JpanelConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpanelConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpanelConfirmarMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CONFIRMAR");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CHECK-IN");

        javax.swing.GroupLayout JpanelConfirmarLayout = new javax.swing.GroupLayout(JpanelConfirmar);
        JpanelConfirmar.setLayout(JpanelConfirmarLayout);
        JpanelConfirmarLayout.setHorizontalGroup(
            JpanelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelConfirmarLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(JpanelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(35, 35, 35))
        );
        JpanelConfirmarLayout.setVerticalGroup(
            JpanelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelConfirmarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        jPanelCancelar.setBackground(new java.awt.Color(102, 0, 0));
        jPanelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCancelarMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CANCELAR");

        javax.swing.GroupLayout jPanelCancelarLayout = new javax.swing.GroupLayout(jPanelCancelar);
        jPanelCancelar.setLayout(jPanelCancelarLayout);
        jPanelCancelarLayout.setHorizontalGroup(
            jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancelarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCancelarLayout.setVerticalGroup(
            jPanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JpanelConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(44, 44, 44)))))
                .addGap(37, 37, 37))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(36, 36, 36)
                .addComponent(JpanelConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 240, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JpanelConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelConfirmarMouseClicked
        String codigoActual = Txt_CodigoReserva.getText().trim();
        String dni = Txt_DniPas.getText().trim();

    // 1. VALIDACIÓN: Que el usuario haya escrito algo en el buscador
    if (codigoActual.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, ingrese o busque un código de reserva primero.", 
                "Falta Código", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        Txt_CodigoReserva.requestFocus();
        return;
    }

    // 2. VALIDACIÓN: Obligar a ingresar el DNI/Pasaporte del huésped
    if (dni.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, ingrese el DNI o Pasaporte del huésped.", 
                "Documento Requerido", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        Txt_DniPas.requestFocus();
        return;
    }

    // 3. PROCESAR Y ACTUALIZAR EN LA TABLA
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    boolean filaActualizada = false;
    boolean yaRealizado = false;

    // Recorremos la tabla buscando el ID
    for (int i = 0; i < modelo.getRowCount(); i++) {
        String idReservaTabla = modelo.getValueAt(i, 0).toString(); // Columna 0: ID Reserva
        String estadoActual = modelo.getValueAt(i, 5).toString();   // Columna 5: Estado Check-in
        
        if (idReservaTabla.equalsIgnoreCase(codigoActual)) {
            // Validamos si ya se le hizo check-in antes
            if (estadoActual.equalsIgnoreCase("REALIZADO")) {
                yaRealizado = true;
                break;
            }
            
            // Si está PENDIENTE, lo cambiamos a REALIZADO
            modelo.setValueAt("REALIZADO", i, 5); 
            filaActualizada = true;
            break;
        }
    }

    // 4. CONCLUSIÓN Y FEEDBACK AL USUARIO
    if (yaRealizado) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Esta reserva ya cuenta con un Check-In REALIZADO.", 
                "Aviso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        limpiarFormulario();
    } else if (filaActualizada) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "¡Check-in confirmado con éxito para la reserva " + codigoActual + "!", 
                "Proceso Terminado", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        limpiarFormulario();
    } else {
        // Si el código no coincide con ninguna fila de la tabla
        javax.swing.JOptionPane.showMessageDialog(this, 
                "El código '" + codigoActual + "' no corresponde a ninguna reserva activa en la tabla.\n"
                + "Por favor, busque una reserva válida antes de confirmar.", 
                "Reserva No Encontrada", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_JpanelConfirmarMouseClicked

    private void Bt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_BuscarActionPerformed
        String codigoBuscar = Txt_CodigoReserva.getText().trim();
    
    // 1. VALIDACIÓN: Campo vacío
    if (codigoBuscar.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, ingrese un código de reserva para buscar.", 
                "Campo Vacío", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        Txt_CodigoReserva.requestFocus();
        return;
    }

    // 2. MATRIZ DE DATOS: Base de datos simulada (incluye tipo de habitación para el ComboBox)
    
    String[][] datosDeOrigen = {
        {"R123", "Juan Pérez", "15/05/2026", "20/05/2026", "Suite Ejecutiva", "PENDIENTE", "2", "1", "305"},
        {"R122", "María López", "15/05/2026", "22/05/2026", "Suite Estándar", "PENDIENTE", "1", "0", "201"},
        {"R124", "Carlos Ruiz", "18/05/2026", "23/05/2026", "Suite Ejecutiva", "PENDIENTE", "2", "0", "306"}
    };

    boolean encontrado = false;

    // 3. BÚSQUEDA DE LA RESERVA
    for (String[] fila : datosDeOrigen) {
        if (fila[0].equalsIgnoreCase(codigoBuscar)) { // Comparación ignorando mayúsculas/minúsculas
            
            // Rellenar etiquetas de texto de la reserva activa
            Jbl_Huesped.setText(fila[1]);
            Jbl_Fentrada.setText(fila[2]);
            Jbl_Fsalida.setText(fila[3]);
            Jbl_Adulto.setText("Adultos: " + fila[6]);
            Jbl_Niños.setText("Niños: " + fila[7]);
            Jbl_HabSug.setText(fila[8]);
            
            // Limpiar campo DNI para el nuevo ingreso y enfocarlo
            Txt_DniPas.setText("");
            Txt_DniPas.requestFocus();
            
            // 4. CARGAR EL COMBOBOX DINÁMICAMENTE SEGÚN EL TIPO DE HABITACIÓN
            String tipoHabitacion = fila[4];
            cargarHabitacionesDisponibles(tipoHabitacion, fila[8]);

            encontrado = true;
            break; // Detener el ciclo al encontrar el registro
        }
    }

    // 5. MESAJE EN CASO DE NO EXISTIR
    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "La reserva con el código '" + codigoBuscar + "' no fue encontrada.", 
                "Reserva No Registrada", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarFormulario();
    }
    }//GEN-LAST:event_Bt_BuscarActionPerformed

    private void Cb_AsigHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_AsigHabActionPerformed
        if (Cb_AsigHab.getSelectedItem() != null) {
        String seleccion = Cb_AsigHab.getSelectedItem().toString();
        // Si selecciona una habitación real (y no el texto por defecto)
        if (!seleccion.equals("Seleccione otra...")) {
            Jbl_HabSug.setText(seleccion); // Actualiza visualmente la habitación asignada
        }
    }
    }//GEN-LAST:event_Cb_AsigHabActionPerformed

    private void jPanelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCancelarMouseClicked
        limpiarFormulario();
    }//GEN-LAST:event_jPanelCancelarMouseClicked

    private void Txt_DniPasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DniPasKeyTyped
        char c = evt.getKeyChar();
    
    // Validar que solo sean números Y que no pase de 10 caracteres
    if (!Character.isDigit(c) || Txt_DniPas.getText().length() >= 10) {
        evt.consume();
    }
    }//GEN-LAST:event_Txt_DniPasKeyTyped

    private void Jb_VolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jb_VolverKeyPressed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jb_VolverKeyPressed

    private void Jb_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jb_VolverMouseClicked
         new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jb_VolverMouseClicked

    private void cargarHabitacionesDisponibles(String tipoHabitacion, String habitacionSugerida) {
    // Limpiamos los elementos previos que tenga el ComboBox
    Cb_AsigHab.removeAllItems();
    
    // Añadimos una opción por defecto
    Cb_AsigHab.addItem("Seleccione otra...");

    // Filtramos y llenamos según el tipo de suite de la reserva actual
    if (tipoHabitacion.equalsIgnoreCase("Suite Ejecutiva")) {
        String[] ejecutivas = {"301", "302", "303", "305", "306", "307"};
        for (String hab : ejecutivas) {
            if (!hab.equals(habitacionSugerida)) { // Evitamos duplicar la sugerida en la lista
                Cb_AsigHab.addItem(hab);
            }
        }
    } else if (tipoHabitacion.equalsIgnoreCase("Suite Estándar")) {
        String[] estandares = {"201", "202", "203", "204", "205"};
        for (String hab : estandares) {
            if (!hab.equals(habitacionSugerida)) {
                Cb_AsigHab.addItem(hab);
            }
        }
    } else {
        // En caso de suites premium u otras categorías (como "Suite Pana")
        String[] otras = {"401", "402", "501"};
        for (String hab : otras) {
            Cb_AsigHab.addItem(hab);
        }
    }
}
    
    private void limpiarFormulario() {
    Txt_CodigoReserva.setText("");
    Txt_DniPas.setText("");
    
    // Restablecer etiquetas a su estado inicial
    Jbl_Huesped.setText("\"\"");
    Jbl_Fentrada.setText("\"\"");
    Jbl_Fsalida.setText("\"\"");
    Jbl_Adulto.setText("Adultos:");
    Jbl_Niños.setText("Niños:");
    Jbl_HabSug.setText("\"\"");
    
    // Limpiar el ComboBox
    Cb_AsigHab.removeAllItems();
    Cb_AsigHab.addItem("Seleccione otra...");
    
    // Regresar el foco al buscador
    Txt_CodigoReserva.requestFocus();
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Buscar;
    private javax.swing.JComboBox<String> Cb_AsigHab;
    private javax.swing.JLabel Jb_Volver;
    private javax.swing.JLabel Jbl_Adulto;
    private javax.swing.JLabel Jbl_Fentrada;
    private javax.swing.JLabel Jbl_Fsalida;
    private javax.swing.JLabel Jbl_HabSug;
    private javax.swing.JLabel Jbl_Huesped;
    private javax.swing.JLabel Jbl_Niños;
    private javax.swing.JPanel JpanelConfirmar;
    private javax.swing.JTextField Txt_CodigoReserva;
    private javax.swing.JTextField Txt_DniPas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
