/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author LENOVO
 */
public class Check_out extends javax.swing.JFrame {

    /**
     * Creates new form Check_out
     */
    public Check_out() {
        initComponents();
        cargarTablaCheckOut(); 
        configurarComboBoxPagos();
    }
    
    private String[][] reservasActivas = {
    {"R123", "Juan Pérez", "15/05/2026", "20/05/2026", "305", "Checked-In", "150.00", "45.00"},
    {"R124", "Carlos Ruiz", "18/05/2026", "23/05/2026", "306", "Checked-In", "200.00", "120.00"},
    {"R125", "Ana Gómez", "19/05/2026", "21/05/2026", "401", "Checked-In", "180.00", "0.00"}
};

private void cargarTablaCheckOut() {
    String[] columnas = {"ID Reserva", "Huésped Principal", "N° Hab", "Estado"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };

    for (String[] fila : reservasActivas) {
        // Solo cargamos a la tabla los que ya hicieron Check-in
        if (fila[5].equals("Checked-In")) {
            modelo.addRow(new Object[]{fila[0], fila[1], fila[4], fila[5]});
        }
    }
    jTable1.setModel(modelo);
}

private void limpiarFormulario() {
    Txt_CodigoH.setText("");
    Jb_Huesped.setText("\"\"");
    Jb_NumNoche.setText("\"\"");
    Jb_PrecioEstancia.setText("$\"\"");
    Jb_SubtotalEstancia.setText("$\"\"");
    Jb_Consumos.setText("$\"\"");
    Jb_Impuestos.setText("$\"\"");
    Jb_TotalCargos.setText("$\"\"");
    
    Jb_NochesResumen.setText("\"\"");
    Jb_CargosResumen.setText("$\"\"");
    Jb_EstadoCuenta.setText("[\"\"]");
    Jb_EstadoCuenta.setForeground(new java.awt.Color(0, 0, 0)); // Color neutro
    
    Cb_MetodoP.setSelectedIndex(0);
    Cb_NumCuotas.setSelectedIndex(0);
    Txt_CodigoH.requestFocus();
}

private void configurarComboBoxPagos() {
   
    Cb_MetodoP.removeAllItems();
    Cb_NumCuotas.removeAllItems();

    //Agregamos las opciones principales de pago
    Cb_MetodoP.addItem("Seleccione...");
    Cb_MetodoP.addItem("De contado");
    Cb_MetodoP.addItem("A crédito");

    // Estado inicial del combo de cuotas (deshabilitado por seguridad)
    Cb_NumCuotas.addItem("-");
    Cb_NumCuotas.setEnabled(false);

    
    Cb_MetodoP.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            String metodoSeleccionado = (String) Cb_MetodoP.getSelectedItem();
            
            // limpiamos las cuotas al cambiar de método
            Cb_NumCuotas.removeAllItems(); 

            if (metodoSeleccionado != null) {
                if (metodoSeleccionado.equals("De contado")) {
                    // Configuración para pago de contado
                    Cb_NumCuotas.addItem("1");
                    Cb_NumCuotas.setSelectedIndex(0);
                    Cb_NumCuotas.setEnabled(false); // Bloqueamos para que no puedan cambiarlo
                    
                } else if (metodoSeleccionado.equals("A crédito")) {
                    // Configuración para pago a crédito (Bucle del 1 al 16)
                    for (int i = 1; i <= 16; i++) {
                        Cb_NumCuotas.addItem(String.valueOf(i));
                    }
                    Cb_NumCuotas.setEnabled(true); // Desbloqueamos para que elijan
                    
                } else {
                    // Estado por defecto ("Seleccione...")
                    Cb_NumCuotas.addItem("-");
                    Cb_NumCuotas.setEnabled(false);
                }
            }
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txt_CodigoH = new javax.swing.JTextField();
        Bt_BuscarH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Jb_Huesped = new javax.swing.JLabel();
        Jb_SubtotalEstancia = new javax.swing.JLabel();
        Jb_Consumos = new javax.swing.JLabel();
        Jb_PrecioEstancia = new javax.swing.JLabel();
        Jb_Impuestos = new javax.swing.JLabel();
        Jb_TotalCargos = new javax.swing.JLabel();
        Jb_NumNoche = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Cb_MetodoP = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        Cb_NumCuotas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Jb_EstadoCuenta = new javax.swing.JLabel();
        Jb_NochesResumen = new javax.swing.JLabel();
        Jb_CargosResumen = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        Jpanel_Cancelar = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Jpanel_ProcesarCheckout = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CHECK-OUT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(631, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 70));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("\"\")");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 60, 40));
        jPanel1.add(Txt_CodigoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, -1));

        Bt_BuscarH.setBackground(new java.awt.Color(153, 0, 0));
        Bt_BuscarH.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Bt_BuscarH.setForeground(new java.awt.Color(255, 255, 255));
        Bt_BuscarH.setText("BUSCAR");
        Bt_BuscarH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        Bt_BuscarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_BuscarHActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_BuscarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 123, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("O seleccione uno de la lista");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("BUSCAR HÚESPED POR CÓDIGO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setText("Húesped");

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setText("Estancia");

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setText("Subtotal Habitación");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel11.setText("Consumos");

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel12.setText("Impuestos");

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel13.setText("Total Cargos");

        Jb_Huesped.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Jb_Huesped.setText("\"\"");

        Jb_SubtotalEstancia.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_SubtotalEstancia.setText("$\"\"");

        Jb_Consumos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_Consumos.setText("$\"\"");

        Jb_PrecioEstancia.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_PrecioEstancia.setText("$\"\"");

        Jb_Impuestos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_Impuestos.setText("$\"\"");

        Jb_TotalCargos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_TotalCargos.setText("$\"\"");

        Jb_NumNoche.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_NumNoche.setText("\"\"");

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel21.setText("METODO DE PAGO");

        Cb_MetodoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel22.setText("Número Cuotas");

        Cb_NumCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jb_NumNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Jb_Huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jb_PrecioEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cb_NumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cb_MetodoP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(63, 63, 63)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jb_TotalCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Jb_Consumos, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(Jb_SubtotalEstancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jb_Impuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Jb_Huesped))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Jb_NumNoche)
                    .addComponent(Jb_PrecioEstancia))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Jb_SubtotalEstancia))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(Jb_Consumos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Jb_Impuestos))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Jb_TotalCargos))
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cb_MetodoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cb_NumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 360, 440));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Húespedes Actualmente Registrados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Resumen de Factura");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 240, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("(Reserva");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 90, 40));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel24.setText("Total de Cargos");

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel25.setText("Estado de Cuenta:");

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel26.setText("Numero de Noches");

        Jb_EstadoCuenta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Jb_EstadoCuenta.setForeground(new java.awt.Color(255, 102, 0));
        Jb_EstadoCuenta.setText("[\"\"]");

        Jb_NochesResumen.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Jb_NochesResumen.setText("\"\"");

        Jb_CargosResumen.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Jb_CargosResumen.setText("$\"\"");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jb_NochesResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jb_CargosResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel25))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Jb_EstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Jb_NochesResumen))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Jb_CargosResumen))
                .addGap(45, 45, 45)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jb_EstadoCuenta)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 280, 240));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, 440));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setText("Detalles de Facturación");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 240, 40));

        Jpanel_Cancelar.setBackground(new java.awt.Color(153, 0, 0));
        Jpanel_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jpanel_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jpanel_CancelarMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CANCELAR");

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Jpanel_CancelarLayout = new javax.swing.GroupLayout(Jpanel_Cancelar);
        Jpanel_Cancelar.setLayout(Jpanel_CancelarLayout);
        Jpanel_CancelarLayout.setHorizontalGroup(
            Jpanel_CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_CancelarLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(Jpanel_CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_CancelarLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_CancelarLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(24, 24, 24))))
        );
        Jpanel_CancelarLayout.setVerticalGroup(
            Jpanel_CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_CancelarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(Jpanel_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 190, 80));

        Jpanel_ProcesarCheckout.setBackground(new java.awt.Color(153, 0, 0));
        Jpanel_ProcesarCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jpanel_ProcesarCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jpanel_ProcesarCheckoutMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("PROCESAR ");

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("CHECK-OUT");

        javax.swing.GroupLayout Jpanel_ProcesarCheckoutLayout = new javax.swing.GroupLayout(Jpanel_ProcesarCheckout);
        Jpanel_ProcesarCheckout.setLayout(Jpanel_ProcesarCheckoutLayout);
        Jpanel_ProcesarCheckoutLayout.setHorizontalGroup(
            Jpanel_ProcesarCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ProcesarCheckoutLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(Jpanel_ProcesarCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        Jpanel_ProcesarCheckoutLayout.setVerticalGroup(
            Jpanel_ProcesarCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ProcesarCheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Jpanel_ProcesarCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 190, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_BuscarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_BuscarHActionPerformed
        String codigoBuscar = Txt_CodigoH.getText().trim();
    
    if (codigoBuscar.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un código de huésped.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean encontrado = false;

    for (String[] fila : reservasActivas) {
        if (fila[0].equalsIgnoreCase(codigoBuscar) && fila[5].equals("Checked-In")) {
            
            long noches = 1; // Valor por defecto
            try {
                // Cálculo de días entre Fecha de Entrada y Salida
                java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                java.time.LocalDate entrada = java.time.LocalDate.parse(fila[2], fmt);
                java.time.LocalDate salida = java.time.LocalDate.parse(fila[3], fmt);
                noches = java.time.temporal.ChronoUnit.DAYS.between(entrada, salida);
                if (noches <= 0) noches = 1; 
            } catch (Exception e) {
                System.out.println("Error calculando fechas. Se asume 1 noche.");
            }

            // Operaciones Matemáticas Financieras
            double tarifa = Double.parseDouble(fila[6]);
            double consumos = Double.parseDouble(fila[7]);
            double subtotal = noches * tarifa;
            double impuestos = (subtotal + consumos) * 0.19; // Ejemplo: 19% IVA
            double total = subtotal + consumos + impuestos;

            
            Jb_Huesped.setText(fila[1]);
            Jb_NumNoche.setText(noches + " Noche(s)");
            Jb_PrecioEstancia.setText(String.format("$%.2f", tarifa));
            Jb_SubtotalEstancia.setText(String.format("$%.2f", subtotal));
            Jb_Consumos.setText(String.format("$%.2f", consumos));
            Jb_Impuestos.setText(String.format("$%.2f", impuestos));
            Jb_TotalCargos.setText(String.format("$%.2f", total));

            // Rellenar Interfaz Gráfica (Sección Resumen de Factura)
            Jb_NochesResumen.setText(String.valueOf(noches));
            Jb_CargosResumen.setText(String.format("$%.2f", total));
            Jb_EstadoCuenta.setText("[PENDIENTE DE PAGO]");
            Jb_EstadoCuenta.setForeground(new java.awt.Color(204, 0, 0)); // Texto en Rojo

            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Huésped no encontrado o ya realizó Check-Out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarFormulario();
       }
    }//GEN-LAST:event_Bt_BuscarHActionPerformed

    private void Jpanel_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpanel_CancelarMouseClicked
       limpiarFormulario();
    }//GEN-LAST:event_Jpanel_CancelarMouseClicked

    private void Jpanel_ProcesarCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpanel_ProcesarCheckoutMouseClicked
        String codigoActual = Txt_CodigoH.getText().trim();
        String metodoPago = Cb_MetodoP.getSelectedItem().toString();
        String cuotas = Cb_NumCuotas.getSelectedItem().toString();

    //Asegurar que hay factura cargada
    if (codigoActual.isEmpty() || Jb_Huesped.getText().equals("\"\"")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Busque un huésped para procesar la facturación.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Método de pago seleccionado (Asumiendo que el índice 0 es "Seleccione...")
    if (Cb_MetodoP.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un método de pago válido.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

   
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    boolean procesado = false;

    for (int i = 0; i < modelo.getRowCount(); i++) {
        if (modelo.getValueAt(i, 0).toString().equalsIgnoreCase(codigoActual)) {
            // Remueve la fila de la tabla de huéspedes activos
            modelo.removeRow(i); 
            procesado = true;
            break;
        }
    }

    
    if (procesado) {
        // Simulador de impresión de factura
        Jb_EstadoCuenta.setText("[FACTURA PAGADA]");
        Jb_EstadoCuenta.setForeground(new java.awt.Color(0, 153, 51)); // Verde
        
        javax.swing.JOptionPane.showMessageDialog(this, 
        "¡Check-Out procesado exitosamente!\n\n" +
        "Huésped: " + Jb_Huesped.getText() + "\n" +
        "Total Cobrado: " + Jb_TotalCargos.getText() + "\n" +
        "Método: " + metodoPago + " (" + cuotas + " cuota/s)\n\n" +
        "Generando comprobante...", 
        "Check-Out Completado", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
        limpiarFormulario();
    }
    }//GEN-LAST:event_Jpanel_ProcesarCheckoutMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String codigoBuscar = Txt_CodigoH.getText().trim();
    
    if (codigoBuscar.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un código de huésped.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean encontrado = false;

    for (String[] fila : reservasActivas) {
        if (fila[0].equalsIgnoreCase(codigoBuscar) && fila[5].equals("Checked-In")) {
            
            long noches = 1; // Valor por defecto
            try {
                // Cálculo de días entre Fecha de Entrada y Salida
                java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                java.time.LocalDate entrada = java.time.LocalDate.parse(fila[2], fmt);
                java.time.LocalDate salida = java.time.LocalDate.parse(fila[3], fmt);
                noches = java.time.temporal.ChronoUnit.DAYS.between(entrada, salida);
                if (noches <= 0) noches = 1; 
            } catch (Exception e) {
                System.out.println("Error calculando fechas. Se asume 1 noche.");
            }

            // Operaciones Matemáticas Financieras
            double tarifa = Double.parseDouble(fila[6]);
            double consumos = Double.parseDouble(fila[7]);
            double subtotal = noches * tarifa;
            double impuestos = (subtotal + consumos) * 0.19; // Ejemplo: 19% IVA
            double total = subtotal + consumos + impuestos;

            // Rellenar Interfaz Gráfica (Sección Detalles de Facturación)
            Jb_Huesped.setText(fila[1]);
            Jb_NumNoche.setText(noches + " Noche(s)");
            Jb_PrecioEstancia.setText(String.format("$%.2f", tarifa));
            Jb_SubtotalEstancia.setText(String.format("$%.2f", subtotal));
            Jb_Consumos.setText(String.format("$%.2f", consumos));
            Jb_Impuestos.setText(String.format("$%.2f", impuestos));
            Jb_TotalCargos.setText(String.format("$%.2f", total));

            // Rellenar Interfaz Gráfica (Sección Resumen de Factura)
            Jb_NochesResumen.setText(String.valueOf(noches));
            Jb_CargosResumen.setText(String.format("$%.2f", total));
            Jb_EstadoCuenta.setText("[PENDIENTE DE PAGO]");
            Jb_EstadoCuenta.setForeground(new java.awt.Color(204, 0, 0)); // Texto en Rojo

            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "Huésped no encontrado o ya realizó Check-Out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarFormulario();
    }
    }//GEN-LAST:event_jTable1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_BuscarH;
    private javax.swing.JComboBox<String> Cb_MetodoP;
    private javax.swing.JComboBox<String> Cb_NumCuotas;
    private javax.swing.JLabel Jb_CargosResumen;
    private javax.swing.JLabel Jb_Consumos;
    private javax.swing.JLabel Jb_EstadoCuenta;
    private javax.swing.JLabel Jb_Huesped;
    private javax.swing.JLabel Jb_Impuestos;
    private javax.swing.JLabel Jb_NochesResumen;
    private javax.swing.JLabel Jb_NumNoche;
    private javax.swing.JLabel Jb_PrecioEstancia;
    private javax.swing.JLabel Jb_SubtotalEstancia;
    private javax.swing.JLabel Jb_TotalCargos;
    private javax.swing.JPanel Jpanel_Cancelar;
    private javax.swing.JPanel Jpanel_ProcesarCheckout;
    private javax.swing.JTextField Txt_CodigoH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
