
package View;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_Correoreg = new javax.swing.JTextField();
        Txt_Usuarioreg = new javax.swing.JTextField();
        Txt_Contraseñareg = new javax.swing.JPasswordField();
        Txt_Nombrereg = new javax.swing.JTextField();
        Bt_Registro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registration-form (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 490));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 490, 80));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 490, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel3.setText("Nombre Completo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setText("Correo Electronico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 40));

        Txt_Correoreg.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Correoreg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Txt_Correoreg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Txt_Correoreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 210, -1));

        Txt_Usuarioreg.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Usuarioreg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Txt_Usuarioreg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Txt_Usuarioreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 210, -1));

        Txt_Contraseñareg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(Txt_Contraseñareg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 210, -1));

        Txt_Nombrereg.setBackground(new java.awt.Color(0, 0, 0));
        Txt_Nombrereg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Txt_Nombrereg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Txt_Nombrereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 210, -1));

        Bt_Registro.setBackground(new java.awt.Color(0, 0, 0));
        Bt_Registro.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        Bt_Registro.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Registro.setText("REGISTRAR CUENTA");
        Bt_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_RegistroActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel7.setBackground(new java.awt.Color(102, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("¿Ya tiene cuenta?");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Bt_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_RegistroActionPerformed
        String nombre = Txt_Nombrereg.getText().trim();
    String correo = Txt_Correoreg.getText().trim();
    String usuario = Txt_Usuarioreg.getText().trim();
    // Convertimos el password de JPasswordField de forma segura
    String contrasena = new String(Txt_Contraseñareg.getPassword());

    // 2. Validamos que el usuario no deje campos vacíos
    if (nombre.isEmpty() || correo.isEmpty() || usuario.isEmpty() || contrasena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Todos los campos son obligatorios para crear la cuenta.", 
                "Campos Incompletos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución aquí si falta rellenar algo
    }

    // 3. Nombre del archivo TXT que actuará como base de datos
    String nombreArchivo = "usuarios_registrados.txt";

    // 4. Intentamos abrir y escribir en el archivo (.txt)
    try (java.io.FileWriter fw = new java.io.FileWriter(nombreArchivo, true);
         java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {
        
        // Escribimos los datos en una nueva línea separados por "|"
        pw.println(nombre + "|" + correo + "|" + usuario + "|" + contrasena);
        
        // Mensaje de confirmación al usuario
        javax.swing.JOptionPane.showMessageDialog(this, 
                "¡Cuenta registrada exitosamente en el sistema!", 
                "Registro Completado", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // 5. Limpiamos los cuadros de texto para que quede listo para otro registro
        Txt_Nombrereg.setText("");
        Txt_Correoreg.setText("");
        Txt_Usuarioreg.setText("");
        Txt_Contraseñareg.setText("");
        Txt_Nombrereg.requestFocus(); // Coloca el cursor de nuevo en el primer campo

    } catch (java.io.IOException e) {
        // Por si ocurre algún problema con los permisos del archivo
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al guardar los datos en el archivo: " + e.getMessage(), 
                "Error de Archivo", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Bt_RegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Registro;
    private javax.swing.JPasswordField Txt_Contraseñareg;
    private javax.swing.JTextField Txt_Correoreg;
    private javax.swing.JTextField Txt_Nombrereg;
    private javax.swing.JTextField Txt_Usuarioreg;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
